name: Create Draft Release

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create
        run: gh release create -d "draft"
  release:
    name: Build and Upload
    needs: create_release
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout egads
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Makefile
      run: make -C src
    - name: Release
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mv egads egads_${{ runner.os }}
        gh release upload "draft" egads_${{ runner.os }}
