name: Create Draft Release

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout egads
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Makefile
      run: make -C src
    - name: Release
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mv egads egads_${{ matrix.os }}
        gh release create -d "draft" egads_${{ matrix.os }}
