name: Create Draft Release

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout egads
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Makefile
      run: make -C egads/src
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          files: egads
